# Generated by Django 4.2.5 on 2023-10-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('facilitator', 'facilitator'), ('team_lead', 'team_lead')], default='student', max_length=20),
        ),
    ]
